---
vault_version: "1.8.2"
vault_checksum: "sha256:d74724d6cc22bf1e1c7c519009b0176809acf6f1c20ee56107de0cab54cd8463"
vault_install_prerequisites: ['unzip']
vault_user: "vault"
vault_group: "vault"
vault_config_path: "/etc/vault.d"
vault_data_path: "/opt/vault/data"